[project]
name = "UFO"
version = "1.0.8"
description = "Source Code for the UFO"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.14",
    "pyaddict>=1.2.1",
    "pyserial-asyncio>=0.6",
    "scipy==1.15.2",
    "uvloop==0.21.0",
]
