name: mypy

on:
    pull_request:
        types:
            - opened
        paths:
            - "src/**.py"
    push:
        paths:
            - "src/**.py"
            - requirements.txt
            - github/workflows/mypy.yaml
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.13
              uses: actions/setup-python@v2
              with:
                  python-version: 3.13
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt mypy
            - name: Run mypy
              working-directory: ./src/ufo-real
              run: |
                  python3 -m mypy . --strict
