name: pylint

on:
    pull_request:
    push:
        paths:
            - "src/ufo-real/**.py"
            - requirements.txt
            - .github/workflows/pylint.yaml
    workflow_dispatch:

jobs:
    build:
        name: pylint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.13
              uses: actions/setup-python@v2
              with:
                  python-version: 3.13
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt pylint
            - name: Run pylint
              working-directory: ./src/ufo-real
              run: |
                  python3 -m pylint *.py */ --rcfile=../../.pylintrc --recursive=y
