name: pylint

on:
    pull_request:
        types:
            - opened
        paths:
            - "src/**.py"
    push:
        paths:
            - "src/**.py"
            - requirements.txt
            - github/workflows/pylint.yaml
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt pylint
            - name: Run pylint
              working-directory: ./src
              run: |
                  python3 -m pylint *.py */ --rcfile=../.pylintrc --recursive=y
